### PR TITLE
Update VertexColor.cginc to fix Android build

### PR DESCRIPTION
**Pull request by marcspraragen**
Addresses issues #125, #540. Builds on solutions presented by Vytek (#213) and antoninklopp (#451)

### CODE REVIEW

**Comment by marcspraragen** [comment]
Note: at first build, variant compilation will throw "identifier not found" errors for the two shaders, but following builds work fine.

**Comment by mhochk** [comment]
There's actually a bigger issue here that I'll get started on a fix for shortly.  The root of the problem is the VertexColor.cginc code was made as a minimalistic wrapper of vertBase/fragBase, but doesn't include support for when UNITY_STANDARD_SIMPLE is set to true (which is apparently the case on Android builds).

This change currently let's you compile for Android, but shouldn't be working correctly for other targets (though I haven't tested to confirm this).  Also even though it compiles for Android, it's not using the shader intended by Unity for Android, so there's probably some kind of fallout there.

**Comment by mhochk** [comment]
Got a fix together and put out PR #547

**Comment by marcspraragen** [comment]
Oh wow thanks! I had noticed this too but didn't have time to set up a fix. I noticed it's up in master branch already.

**Pull request closed without merging**
