### PR TITLE
Initial request to show the proposed pathing changes

### PR DESCRIPTION
**Pull request by MSblgross**
- Change contains no code change or function file renaming
- Created directory for engine agnostic/schema code called GLTFSerialization which contains two projects GLTFSerialization and GLTFSerializationUWP
- We should probably manually merge this change into a branch off of master and then the remaining pull requests can be based off of that

### CODE REVIEW

**Comment by robertlong** [comment]
Looks good to me. Thanks Blake!

**Comment by robertlong** [comment]
There are still references to UnityEngine inside the GLTFSerialization project. The GLTF Math classes and JSONExtensions should be added to the PR before merging. My testing was done incorrectly and I missed this. @MSblgross could you add these changes and resubmit?

**Comment by MSblgross** [comment]
@robertlong That's why I thought this change should go into separate branch. The next PR is going to be my changes to make everything work. This one was just file changes.

**Comment by robertlong** [comment]
Yeah, that makes sense now. Thanks for dividing those up.

**Pull request merged**
