### PR TITLE
Setup Travis build as https://github.com/KhronosGroup/UnityGLTF/issues/64

### PR DESCRIPTION
**Pull request by Vytek**
This is a Travis-ci.org system to build GLTFSeralization and create UnityGLTF.unitypackage and deploy on GitHub Release.

Please see RAW Log:

https://api.travis-ci.org/v3/job/351353968/log.txt

The UnityPackage is created.

### CODE REVIEW

**Comment by stevenvergenz** [comment]
Is it possible to generate packages for multiple Unity versions? Strictly speaking, this project supports 5.6+, not just 2017.3

**Comment by Vytek** [comment]
Yes, the script using https://github.com/sttz/install-unity so you had to modify script:

```javascript
install-unity.py --package Unity 5.6
```

**Comment by blgrossMS** [comment]
Thanks for contributing this!

**Comment by Vytek** [comment]
I had to modify deploy part with your code:

See: https://www.victorhurdugaci.com/github-releases-travis
(WARNING USE:  travis encrypt for your github oauht token!

**Pull request merged**
